/*
 * This file is generated by jOOQ.
*/
package com.money.transfer.db.schema;


import javax.annotation.Generated;

import com.money.transfer.db.tables.Account;


/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>PUBLIC.ACCOUNT</code>.
     */
    public static final Account ACCOUNT = com.money.transfer.db.tables.Account.ACCOUNT;
}
